### ISSUE TITLE
bauzeit

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-fortifications#17]

**Comment by nomisum** [comment]
would be a nice enhancement. i currently limit the process by allowing a single item in the inventory at once, so the distance between truck and building slows the process.

**Comment by McDiod** [comment]
72edb6ed0f27b6ca3453d1ba5a0dcdefbf258907

Leider nicht animiert aus dem Boden rauswachsend, weil's dann wieder Probleme gibt, wenn man's z.B. auf einem Turm platziert.
