### ISSUE TITLE
Not sure why not working for me yet

### ISSUE THREAD

**Issue by anfo55** [gruppe-adler/grad-fortifications#23]
Not sure if my query has been addressed as most closed issues are in Deutsch.
So I have attempted to try this script by following your wiki to install into description.ext and scripts in modules\grad-fortifications\
I have left the example class CfgGradFortifications as unchanged from the wiki just so I can test. When I get into the game however I have no fortifications (Land_BagFence_Long_F or Land_HBarrier_5_F) in which I can place via ACE interaction. I have also placed B_Truck_01_box_F and have no interaction on that either.
Do you have any guesses as to what I might be missing?

**Comment by nomisum** [comment]
did you one of:
```
[player,"Land_BagFence_Corner_F"] call grad_fortifications_fnc_addFort;
[truck_1,"Land_HBarrier_1_F",5] call grad_fortifications_fnc_addFort;
```
you still have to add every item via function to the player or vehicle (additionally to the configuration of values in description.ext)

**Comment by anfo55** [comment]
Oh I see, thank you @nomisum 
These I think would be added to init.sqf or object init?

**Comment by nomisum** [comment]
either way, if object init you can use `this` as well as an identifier

**Comment by anfo55** [comment]
Found it, wonderful! Goodbye Plank!

**Comment by McDiod** [comment]
To add to what nomi said: You only need to configure fortifications or vehicles if you don't like the default behavior. So no need to add every single fortification class that you want to use to the config.
