### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anfo55** [gruppe-adler/grad-fortifications#24]
My apologies, I should have asked in my last (now closed) issue about init syntax. @nomisum kindly solved an issue by letting me know about missing code in init.sqf. That being:

`[player,"Land_BagFence_Corner_F"] call grad_fortifications_fnc_addFort;
[truck_1,"Land_HBarrier_1_F",5] call grad_fortifications_fnc_addFort;`

However I am now wondering that if I want 20 different fortifications in a truck called  `truck_1`, do I have to enter in init.sqf:

`
[truck_1,"object_classname1",5] call grad_fortifications_fnc_addFort;
[truck_1,"object_classname2",2] call grad_fortifications_fnc_addFort;
[truck_1,"object_classname3",7] call grad_fortifications_fnc_addFort;`
etc... up to 20?

Or can I put into a single array? Like:

`[truck_1,["object_classname1",5, "object_classname2",2]] call grad_fortifications_fnc_addFort;`

**Comment by nomisum** [comment]
Indeed you need to call 20 times for 20 different classnames. 

If you want a clean init.sqf, just write your own function with all calls and execute only this one from init.

**Comment by anfo55** [comment]
May I ask which method was used in the example in the Fortifications Wiki?

**Comment by nomisum** [comment]
I dont get your question. There is only one method to add fortifications and you citated it correctly already. One call per classname.

**Comment by McDiod** [comment]
https://community.bistudio.com/wiki/forEach

```sqf
{[truck_1,_x select 0,_x select 1] call grad_fortifications_fnc_addFort} forEach [
    ["object_classname1",5],
    ["object_classname2",2],
    ["object_classname3",7]
];
```
