### ISSUE TITLE
Error with bounding box

### ISSUE THREAD

**Issue by AdmiralGreene** [gruppe-adler/grad-fortifications#28]
Receiving this error when attempting to place an item using the tool, unable to actually place down item or exit out of fortifications placement mode after attempting.

13:18:43 Error in expression <gBox = (boundingBoxReal _obj) apply {_x vectorAdd _boundingBoxOffset};
_bounding>
13:18:43   Error position: <vectorAdd _boundingBoxOffset};
_bounding>
13:18:43   Error vectoradd: Type Number, expected Array
13:18:43 File modules\grad-fortifications\functions\collision\fn_getBoundingLines.sqf [GRAD_fortifications_fnc_getBoundingLines], line 3
13:18:43 Error in expression <gBox = (boundingBoxReal _obj) apply {_x vectorAdd _boundingBoxOffset};
_bounding>

**Comment by McDiod** [comment]
Thanks for the report, this is fixed in [0.9.2](https://github.com/gruppe-adler/grad-fortifications/releases/tag/0.9.2).
